config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cocktails do
    resources :doses, only: [:new, :create] # Important to understand this
  end

  resources :doses, only: [:destroy] # Important to understand this

  root to: 'cocktails#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  attr_accessor :cocktails_ingredients

  has_many :ingredients, through: :doses # Important to notice when setting up schema
  has_many :doses, dependent: :destroy

  accepts_nested_attributes_for :ingredients, allow_destroy: true
  accepts_nested_attributes_for :doses, allow_destroy: true

  mount_uploader :photo, PhotoUploader

  validates :name, uniqueness: true, presence: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :ingredient
  belongs_to :cocktail, dependent: :destroy

  accepts_nested_attributes_for :ingredient, allow_destroy: false

  validates :description, presence: true
  validates_uniqueness_of :ingredient, scope: [:cocktail]
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses

  validates :name, uniqueness: true, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController

  before_action :set_cocktail, only: [:show]

  def index
    @cocktails = Cocktail.all
  end

  def show
  end

  def new
    @cocktail = Cocktail.new()
    @dose = Dose.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  private

  def set_cocktail
    @cocktail = Cocktail.find(params[:id])
  end

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo, :photo_cache, ingredients_attributes: [:id, :name, :_destroy], doses_attributes: [:id, :description, :_destroy])

  end


end

app/controllers/doses_controller.rb
class DosesController < ApplicationController

  before_action :set_cocktail, only: [:new, :create]

  def new
    @dose = Dose.new()
  end

  def create
    # @cocktail = Cocktail.find(dose_params[:cocktail_id]) # Do we need this?
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail

    if @dose.save
      redirect_to @cocktail
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
  end

  private

  def set_cocktail
    @cocktail = Cocktail.find(params[:cocktail_id]) # Important
  end

  def dose_params
    params.require(:dose).permit(:description, :cocktail_id, :ingredient_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/index.html.erb
<div class="title" style="background-image: url('<%= image_path "sexy-girl-at-bar-counter.jpg" %>')">
  <h1 class="jumbo-title strike white-highlight">All Cocktails</h1><br>
  <p class="title-quote white-highlight"><em>you must be the cocktail you wish to see in the world</em> - Gandhi</p>
</div>


<div class="wrapper">
    <div class="list-box">

      <% @cocktails.each do |c| %>
        <div class='card' style="background-image: url('<%=c.photo%>');background-size:cover">
          <%= link_to c.name, cocktail_path(c), { class: 'btn btn-strike' } %>
          <p class='cocktail-ingredients'>
            <% c.doses.each do |dose| %>
              <%= dose.ingredient.name %>
            <% end %>
          </p>
        </div>
      <% end %>
    </div><!-- /list-box -->
  </div><!-- /rounded-box -->
</div><!-- /wrapper -->

app/views/cocktails/new.html.erb
<div class='wrapper dark-bg'>
<div class="container">
<div class="col-xs-12 col-sm-offset-3 col-sm-6">

<h2 class="strike">Cocktail Creator</h2>
<br><br>
<div class="form-box box-shadow">

<%= simple_form_for [@cocktail] do |f| %>
  <%= f.input :name %>Please enter a name for your cocktail.
  <br>
  <br>
  <%= nested_form_for @cocktail do |c_f| %>

  <%= c_f.label "Ingredients" %>



    <%= c_f.fields_for :ingredients do |i_f| %>
      <%= i_f.collection_select(:id, Ingredient.order('name ASC'), :id, :name) %>
      <% @ingredient = Ingredient.find(822) %>

        <%= i_f.fields_for :doses do |d_f| %>
          @ <%= d_f.text_field :description, size: 5, value: "5ml" %>

        <% end %>
      <%= c_f.link_to_remove "Remove this ingredient" %>
                <br>
                <br>
      <% end %>
    <p> <%= c_f.link_to_add "Add an ingredient", :ingredients %></p>

  <% end %>

  <%= f.input :photo %>Please upload a photo. Photos must be under 1 MB.
  <br>
  <br>
  <%= f.input :photo_cache, as: :hidden %>

  <%= f.button :submit, class: 'btn btn-strike btn-right' %>
  <% end %>
</div><!-- form-box -->
</div><!-- column -->
</div><!-- container -->
</div><!-- wrapper -->

app/views/cocktails/show.html.erb
<div class="wrapper">
  <div class="container">
      <div class="title">
        <h1><%= @cocktail.name %></h1>
      </div>
       <div class="list-box">


      <h4>Doses:</h4>
      <div class="dose-box">
      <ul>
      <% @cocktail.doses.each do |dose| %>
        <li><%= dose.ingredient.name %> - <%= dose.description %></li>
      <% end %>
      </ul>
      </div>
    </div>
  </div>
</div>

<%= link_to "Back", cocktails_path %>

app/views/doses/index.html.erb
<div class="title">
  <h1>All Doses</h1>
</div>

<ul>
<% @doses.each do |d| %>
  <li><%= link_to, d.name, dose_path(d) %></li>
<% end %>

app/views/doses/new.html.erb
<%= render 'shared/newdose' %>

app/views/doses/show.html.erb
<h1>Dose Detail</h1>

Description: <%= @dose.description %><br>
Cocktail: <%= @dose.cocktail_id %><br>
Ingredient: <%= @dose.ingredient_id %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title_tag).blank? ? "Monsieur Cocktail" : yield(:title_tag) %></title>

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  </head>

  <%= render 'shared/navbar' %>

  <body>
    <%= yield %>
  </body>

  <%= render 'shared/footer' %>

</html>

app/views/pages/home.html.erb
<%= cl_image_tag("THE_IMAGE_ID_FROM_LIBRARY",
      width: 400, height: 300, crop: :fill) %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png" %>
  <% end %>
  <h5><em>"to cocktail, or not to cocktail? that is the cocktail" - Shakespeare</em></h5>
  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Search form -->
    <form action="" class="navbar-wagon-search">
      <input type="text" class="navbar-wagon-search-input" placeholder="Search something">
      <button type="submit" class="navbar-wagon-search-btn">
        <i class="fa fa-search"></i>
      </button>
    </form>

    <!-- Notification -->
    <%= link_to "#", class: "navbar-wagon-item navbar-wagon-link" do %>
      <div class="badge-container">
        <i class="fa fa-envelope-o"></i>
        <div class="badge badge-blue">3</div>
      </div>
    <% end %>

    <!-- Profile picture and dropdown -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <%= image_tag "http://placehold.it/30x30", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li>
            <%= link_to "#" do %>
              <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
            <% end %>
          </li>
          <li>
            <%= link_to "#" do %>
              <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>

    <!-- Button (call-to-action) -->
    <%= link_to "New Cocktail", "cocktails/new", class: "navbar-wagon-item navbar-wagon-button btn" %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_newdose.html.erb
<h1>New Dose</h1>

<%= simple_form_for [@cocktail, @dose] do |f| %>
  <%= f.input :description %>
  <%= f.input :ingredient_id, collection: Ingredient.all %>
  <%= simple_fields_for :doses do |d_f| %>
    <%= d_f.input :description %>
  <%= f.button :submit %>
<% end %>